import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export type Data = {
  quote: string;
  author: string;
};

const Home: NextPage = () => {
  const [data, setData] = useState<Data[]>([]);
  const [currentQuote, setCurrentQuote] = useState<number>(0);
  useEffect(() => {
    const fetchQuotes = async () => {
      const response = await fetch("/api/hello", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        throw new Error(`Error: ${response.status}`);
      }
      const data = await response.json();
      setData(data);
      setCurrentQuote(Math.floor(Math.random() * data.length));
    };
    fetchQuotes();
  }, []);

  const handleClick = () => {
    setCurrentQuote(Math.floor(Math.random() * data.length));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Random Quote Machine</title>
        <meta
          name="description"
          content="Generated by create next app for freecodecamp frontend"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Random <a href="#">Quote Machine!</a>
        </h1>

        <p className={styles.description}>
          Get started by playing{" "}
          <code className={styles.code}>With Next Quote</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card} id="quote-box">
            <p id="text">{data[currentQuote]?.quote}</p>
            <h2 id="author">- {data[currentQuote]?.author} </h2>
            <div className={styles.buttons}>
              <button
                id="new-quote"
                onClick={handleClick}
                className={styles.cta}
              >
                Next Quote &rarr;
              </button>
              <a id="tweet-quote" href="https://twitter.com/intent/tweet">
                Tweet
              </a>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="http://zarnimyo" target="_blank" rel="noopener noreferrer">
          By &nbsp;<b>Zar Ni Myo</b>
        </a>
      </footer>
    </div>
  );
};

export default Home;
